### ISSUE TITLE
[建议] 增加栏目“网络”，“linux”和”算法“，我可以提供相关书籍

### ISSUE THREAD

**Issue by xkenmon** [threerocks/studyFiles#23]
### linux
* 《鸟哥的Linux私房菜》
### 算法
* 《算法：第四版》
* 《大话数据结构》
* 《啊哈，算法》
* 《坐在马桶上学算法》
* 《点滴算法》
* 《leetbook》
### 网络
* 《HTTP权威指南》
* 《TCP-IP协议详解》

如果能加个java专栏也可以，我的java资源有很多

![image](https://user-images.githubusercontent.com/21695962/44696477-53175380-aaaa-11e8-89f4-ad9d0802050f.png)

**Comment by guanpengchn** [comment]
@xkenmon 老兄我这边也在整理，有没有兴趣讨论下，这是我整理的[awesome-books](https://github.com/guanpengchn/awesome-books)
